#!/bin/sh

###############################################################################
##  git_linux_resources/bash/screen
##     functions to use screen
##
##     requires bash/functions
# see ../readme.md

function screens() {
    /usr/bin/ssh -tAp $BASTION_PORT $BASTION_USERNAME@$BASTION_SERVER "screen -ls"
}

function jscreen() {
    if [ -z $1 ]
    then
        echo "Usage: jscreen ssh-destination [ssh-command]"
    else
        DEST=$1  #we know if we are here, we have at least a $1
	      SCREEN_TITLE=$DEST
        shift
        if [ -z "$1" ]; then
            if [ -n $DEBUG ]; then
                echo "running: screen -S $DEST -t $SCREEN_TITLE -D -R /usr/bin/ssh -t -A $DEST"
            fi
            screen -S $DEST -t $SCREEN_TITLE -D -R /usr/bin/ssh -t -A  $DEST
        else
            if [ -n $DEBUG ]; then
                echo "running screen -S $DEST -t $SCREEN_TITLE -D -R \"/usr/bin/ssh -t -A $DEST \"$@\""
            fi
            screen -S $DEST -t $SCREEN_TITLE -D -R "/usr/bin/ssh -t -A $DEST \"$@\""
        fi
    fi
}

function restore() {
    if [ -z "$1" ]; then
        for i in $(screens | awk '/tached/ {print $1}' | cut -d. -f2)
        do
            echo restoring $i...
            terminator -x ssh -tA jump screen -R -D $i

        done
    elif [ "$1" = "-h" ]; then
        echo " USAGE: restore [screen]"
    else
        RESTORED=""
        for i in $(screens | awk '/tached/ {print $1}' | cut -d. -f2); do
            if [ "$1" = "$i" ]; then
                echo "Restoring session to $1..."
                terminator -x ssh -tA jump screen -D -R $1
                RESTORED="yay"
            fi
        done
        if [ -z "$RESTORED" ]; then
            echo "Session to $1 not found!"
        fi
    fi

}
